---
# configure and (re)start telegraf and make sure it's enabled

- name: Create Telegraf config file
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_configuration_dir }}/telegraf.conf"
  notify:
    - 'restart telegraf'

- name: Output destination file name for custom Telegraf config
  debug:
    msg: "{{ (telegraf_custom_config_file|basename).split('.')|first }}.conf"
  when: telegraf_custom_config_file is defined

- name: Create additional Telegraf config from given template/file
  template:
    src: "{{ telegraf_custom_config_file }}"
    dest: "{{ telegraf_configuration_dir }}/telegraf.d/{{ (telegraf_custom_config_file|basename).split('.')|first }}.conf"
  when: telegraf_custom_config_file is defined
  notify:
    - 'restart telegraf'

- name: Register telegraf deamon to start on bootup
  service:
    name: telegraf
    enabled: yes

- name: Check status
  command: service telegraf status
